export const ADD_TODO = 'ADD_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const  UPDATE_TODO = 'UPDATE_TODO'
export const FILTER_DONE = 'FILTER_DONE'
export const FILTER_NOT_DONE = 'FILTER_NOT_DONE'
export const SHOW_ALL = 'SHOW_ALL'
export const DELETE_TODO = 'DELETE_TODO'